# special exceptions for known issues
raw_title_prefixes:
  - "www.Torrenting.com -"



#for entry in extracted_data:
#    if media_type == 'tv_show':
#    if entry['tv_show_name'] == '60 Minutes (US)':
#         entry['tv_show_name'] = '60 Minutes'