name: Docker Build

on:
  push:
    branches: [ dev-agent, dev, stg, main ]
  pull_request:
    branches: [ dev, stg, main ]

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}

jobs:
  docker-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      run: |
        # Generate tags based on branch/PR
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          TAGS="${{ env.IMAGE_PREFIX }}/at-base:pr-${{ github.event.number }}"
          echo "BASE_TAG=pr-${{ github.event.number }}" >> $GITHUB_ENV
        elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          TAGS="${{ env.IMAGE_PREFIX }}/at-base:latest,${{ env.IMAGE_PREFIX }}/at-base:main,${{ env.IMAGE_PREFIX }}/at-base:sha-${{ github.sha }}"
          echo "BASE_TAG=latest" >> $GITHUB_ENV
        else
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          TAGS="${{ env.IMAGE_PREFIX }}/at-base:${BRANCH_NAME},${{ env.IMAGE_PREFIX }}/at-base:sha-${{ github.sha }}"
          echo "BASE_TAG=${BRANCH_NAME}" >> $GITHUB_ENV
        fi
        echo "TAGS=$TAGS" >> $GITHUB_ENV
        echo "Tags: $TAGS"

    - name: Build and push base image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./containerization/dockerfile.00_base
        push: true
        tags: ${{ env.TAGS }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push service images
      run: |
        set -e
        echo "Building service images with base image: ${{ env.IMAGE_PREFIX }}/at-base:${{ env.BASE_TAG }}"
        
        # List of services to build
        services=(
          "01_rss_ingest:rss-ingest"
          "02_collect:collect"
          "03_parse:parse"
          "04_file_filtration:file-filtration"
          "05_metadata_collection:metadata-collection"
          "06_media_filtration:media-filtration"
          "07_initiation:initiation"
          "08_download_check:download-check"
          "09_transfer:transfer"
          "10_cleanup:cleanup"
        )
        
        # Build each service
        for service_info in "${services[@]}"; do
          IFS=':' read -r dockerfile service_name <<< "$service_info"
          
          echo "Building ${service_name}..."
          
          # Generate service tags
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            SERVICE_TAGS="${{ env.IMAGE_PREFIX }}/${service_name}:pr-${{ github.event.number }}"
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            SERVICE_TAGS="${{ env.IMAGE_PREFIX }}/${service_name}:latest,${{ env.IMAGE_PREFIX }}/${service_name}:main,${{ env.IMAGE_PREFIX }}/${service_name}:sha-${{ github.sha }}"
          else
            BRANCH_NAME=${GITHUB_REF#refs/heads/}
            SERVICE_TAGS="${{ env.IMAGE_PREFIX }}/${service_name}:${BRANCH_NAME},${{ env.IMAGE_PREFIX }}/${service_name}:sha-${{ github.sha }}"
          fi
          
          # Build and push the service image
          docker buildx build \
            --build-arg BASE_IMAGE=${{ env.IMAGE_PREFIX }}/at-base:${{ env.BASE_TAG }} \
            --file ./containerization/dockerfile.${dockerfile} \
            --tag ${SERVICE_TAGS//,/ --tag } \
            --push \
            --cache-from type=gha \
            --cache-to type=gha,mode=max \
            .
        done

    - name: Report build summary
      if: always()
      run: |
        echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "- Base image: ${{ env.IMAGE_PREFIX }}/at-base:${{ env.BASE_TAG }}" >> $GITHUB_STEP_SUMMARY
        echo "- Total build time: $((SECONDS / 60)) minutes $((SECONDS % 60)) seconds" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Images pushed:" >> $GITHUB_STEP_SUMMARY
        echo "- at-base" >> $GITHUB_STEP_SUMMARY
        echo "- rss-ingest" >> $GITHUB_STEP_SUMMARY
        echo "- collect" >> $GITHUB_STEP_SUMMARY
        echo "- parse" >> $GITHUB_STEP_SUMMARY
        echo "- file-filtration" >> $GITHUB_STEP_SUMMARY
        echo "- metadata-collection" >> $GITHUB_STEP_SUMMARY
        echo "- media-filtration" >> $GITHUB_STEP_SUMMARY
        echo "- initiation" >> $GITHUB_STEP_SUMMARY
        echo "- download-check" >> $GITHUB_STEP_SUMMARY
        echo "- transfer" >> $GITHUB_STEP_SUMMARY
        echo "- cleanup" >> $GITHUB_STEP_SUMMARY